const API='https://osirisai.live/api';
const CELESTRAK='https://celestrak.org/NORAD/elements/gp.php';
const state={satellites:[],earthquakes:[],flights:[],stats:null,selected:null};
const orbitCache=new Map();
const $=id=>document.getElementById(id);
const map=new maplibregl.Map({container:'map',style:{version:8,sources:{carto:{type:'raster',tiles:['https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png','https://b.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap © CARTO'}},layers:[{id:'background',type:'background',paint:{'background-color':'#05070b'}},{id:'carto',type:'raster',source:'carto',paint:{'raster-opacity':.82}}],projection:{type:'globe'}},center:[0,20],zoom:1.35,dragRotate:true,renderWorldCopies:false});
map.addControl(new maplibregl.NavigationControl({showCompass:true}),'bottom-right');
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function setConnection(ok){$('connection').textContent=ok?'LIVE':'OFFLINE';$('apiState').textContent=ok?'LIVE DATA':'API UNAVAILABLE'}
function asArray(data,keys=[]){if(Array.isArray(data))return data;for(const k of keys)if(Array.isArray(data?.[k]))return data[k];return []}
function coords(o){const lat=Number(o.latitude??o.lat??o.sat_lat??o.latitude_deg),lon=Number(o.longitude??o.lon??o.lng??o.sat_lon??o.longitude_deg);return Number.isFinite(lat)&&Number.isFinite(lon)?[lon,lat]:null}
function clearLayer(id){if(map.getLayer(id))map.removeLayer(id);if(map.getSource(id))map.removeSource(id)}
function addPoints(id,items,color,click){clearLayer(id);const features=items.map((o,i)=>{const c=coords(o);return c?{type:'Feature',geometry:{type:'Point',coordinates:c},properties:{...o,_i:i}}:null}).filter(Boolean);map.addSource(id,{type:'geojson',data:{type:'FeatureCollection',features}});map.addLayer({id,type:'circle',source:id,paint:{'circle-radius':['interpolate',['linear'],['zoom'],1,2.5,4,4.5,8,6],'circle-color':color,'circle-opacity':.9,'circle-stroke-width':1,'circle-stroke-color':'#fff','circle-stroke-opacity':.35}});map.on('click',id,e=>{const p=e.features?.[0]?.properties||{};click(p)});map.on('mouseenter',id,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',id,()=>map.getCanvas().style.cursor='')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function satelliteName(s){return String(s.name||s.satellite_name||s.object_name||s.OBJECT_NAME||s.object||'UNKNOWN SATELLITE')}
function satelliteId(s){return String(s.norad_id??s.noradId??s.catalog_number??s.NORAD_CAT_ID??s.id??'')}
function objectDetail(p,type){let title=p.name||p.satellite_name||p.OBJECT_NAME||p.callsign||p.icao24||type.toUpperCase();let rows=type==='satellite'?[['NORAD',p.norad_id??p.noradId??p.NORAD_CAT_ID??'—'],['LAT',p.latitude??p.lat??'—'],['LON',p.longitude??p.lon??'—'],['ALT',p.altitude??p.alt_km??'—'],['TYPE',p.type??p.object_type??'ORBITAL OBJECT'],['SOURCE','OSIRIS / CELESTRAK GP']]:type==='earthquake'?[['MAG',p.magnitude??p.mag??'—'],['DEPTH',p.depth??p.depth_km??'—'],['PLACE',p.place??p.location??'—']]:[['CALLSIGN',p.callsign??'—'],['ALT',p.altitude??'—'],['SPEED',p.velocity??p.speed??'—'],['HEADING',p.heading??'—']];$('detailCard').innerHTML='<div class="card-kicker">SELECTED OBJECT</div><h2>'+escapeHtml(title)+'</h2>'+rows.map(r=>'<p style="margin:7px 0;color:#9baab4"><span style="color:#596873;font-size:8px;letter-spacing:.12em">'+escapeHtml(r[0])+'</span><br>'+escapeHtml(String(r[1]))+'</p>').join('')}
function findTle(s){const l1=s.tle_line1??s.tle1??s.line1??s.TLE_LINE1??s.tle?.line1,l2=s.tle_line2??s.tle2??s.line2??s.TLE_LINE2??s.tle?.line2;return l1&&l2?[String(l1),String(l2)]:null}
function findOmm(s){return s&&s.MEAN_MOTION!=null&&s.ECCENTRICITY!=null&&s.INCLINATION!=null&&s.RA_OF_ASC_NODE!=null&&s.ARG_OF_PERICENTER!=null&&s.MEAN_ANOMALY!=null&&s.EPOCH?s:null}
async function getOrbitalElements(s){const direct=findTle(s);if(direct)return {kind:'tle',data:direct};const directOmm=findOmm(s);if(directOmm)return {kind:'omm',data:directOmm};const id=satelliteId(s);if(!id)return null;if(orbitCache.has(id))return orbitCache.get(id);const url=`${CELESTRAK}?CATNR=${encodeURIComponent(id)}&FORMAT=JSON`;try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('CelesTrak HTTP '+r.status);const json=await r.json();const record=Array.isArray(json)?json[0]:json?.data?.[0]||json?.[0]||json;if(!record)throw new Error('No GP record');const result={kind:'omm',data:record};orbitCache.set(id,result);return result}catch(e){console.warn('CelesTrak GP lookup failed',e);return null}}
async function drawOrbit(s){clearLayer('selected-orbit');if(typeof satellite==='undefined'){toast('Orbit engine failed to load');return false}const elements=await getOrbitalElements(s);if(!elements){toast('No current orbital elements found');return false}try{const satrec=elements.kind==='tle'?satellite.twoline2satrec(elements.data[0],elements.data[1]):satellite.json2satrec(elements.data),now=new Date(),segments=[],current=[];for(let m=-90;m<=90;m+=2){const d=new Date(now.getTime()+m*60000),pv=satellite.propagate(satrec,d);if(!pv?.position)continue;const gmst=satellite.gstime(d),g=satellite.eciToGeodetic(pv.position,gmst),lon=satellite.degreesLong(g.longitude),lat=satellite.degreesLat(g.latitude),point=[lon,lat];if(current.length&&Math.abs(point[0]-current[current.length-1][0])>180){if(current.length>1)segments.push({type:'Feature',geometry:{type:'LineString',coordinates:current.splice(0)}});current.push(point)}else current.push(point)}if(current.length>1)segments.push({type:'Feature',geometry:{type:'LineString',coordinates:current}});if(!segments.length)throw new Error('No propagated orbit points');map.addSource('selected-orbit',{type:'geojson',data:{type:'FeatureCollection',features:segments}});map.addLayer({id:'selected-orbit',type:'line',source:'selected-orbit',paint:{'line-color':'#47e7ff','line-width':2,'line-opacity':.82,'line-dasharray':[2,2]}});return true}catch(e){console.error('Orbit propagation failed',e);toast('Orbit calculation failed');return false}}
async function focusSatellite(s){const c=coords(s);if(!c)return toast('Satellite has no map coordinates');state.selected=s;map.flyTo({center:c,zoom:4.6,duration:1300});objectDetail(s,'satellite');document.querySelectorAll('.layer').forEach(b=>{if(b.dataset.layer==='satellites')b.classList.add('active')});updateVisibility();if($('orbitMode').checked){toast('Loading orbital elements…');if(await drawOrbit(s))toast('Tracking '+satelliteName(s)+' • orbit path active')}else toast('Tracking '+satelliteName(s))}
function searchSatellites(q){const query=q.trim().toLowerCase(),box=$('searchResults');if(!query){box.innerHTML='';box.classList.remove('show');return}const matches=state.satellites.filter(s=>(satelliteName(s)+' '+satelliteId(s)).toLowerCase().includes(query)).slice(0,7);box.innerHTML=matches.length?matches.map((s,i)=>'<button class="search-result" data-index="'+i+'"><strong>'+escapeHtml(satelliteName(s))+'</strong><small>NORAD '+escapeHtml(satelliteId(s)||'—')+'</small></button>').join(''):'<div class="search-result"><strong>No matching satellite</strong><small>Try a name or NORAD ID</small></div>';box.classList.add('show');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{focusSatellite(matches[Number(b.dataset.index)]);box.classList.remove('show');$('search').value=''})}
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw new Error(path+' '+r.status);return r.json()}
async function load(){ $('apiState').textContent='FETCHING…';try{const [stats,sats,quakes,flights]=await Promise.all([get('/stats'),get('/satellites'),get('/earthquakes'),get('/flights')]);state.stats=stats?.stats||stats;state.satellites=asArray(sats,['satellites','objects']);state.earthquakes=asArray(quakes,['earthquakes','events']);state.flights=asArray(flights,['flights','aircraft']);if(!state.flights.length&&Array.isArray(flights?.commercial_flights))state.flights=flights.commercial_flights;$('satCount').textContent=state.satellites.length||state.stats?.sats||'—';$('quakeCount').textContent=state.earthquakes.length||'—';$('flightCount').textContent=state.flights.length||state.stats?.flights||'—';$('statSats').textContent=state.stats?.sats??state.satellites.length??'—';$('statFlights').textContent=state.stats?.flights??state.flights.length??'—';$('statEvents').textContent=state.stats?.incidents??state.earthquakes.length??'—';$('statWeather').textContent=state.stats?.weather??'—';const totals=['sats','flights','incidents','weather'].map(k=>Number(state.stats?.[k])).filter(Number.isFinite);$('totalCount').textContent=totals.length?totals.reduce((a,b)=>a+b,0).toLocaleString():'—';addPoints('satellites',state.satellites,'#47e7ff',p=>{const s=state.satellites[Number(p._i)];focusSatellite(s||p)});addPoints('earthquakes',state.earthquakes,'#ffc857',p=>objectDetail(p,'earthquake'));addPoints('flights',state.flights,'#5b8cff',p=>objectDetail(p,'flight'));updateVisibility();if(state.selected&&$('orbitMode').checked)drawOrbit(state.selected);$('lastUpdate').textContent=new Date().toISOString().replace('T',' ').slice(0,19)+' UTC';setConnection(true);toast('Live OSIRIS data updated')}catch(e){console.error(e);setConnection(false);toast('OSIRIS API unavailable — retry later')}}
function updateVisibility(){for(const id of ['satellites','earthquakes','flights'])if(map.getLayer(id))map.setLayoutProperty(id,'visibility',document.querySelector(`[data-layer="${id}"]`).classList.contains('active')?'visible':'none');if(map.getLayer('selected-orbit'))map.setLayoutProperty('selected-orbit','visibility',$('orbitMode').checked?'visible':'none')}
function resetView(){map.flyTo({center:[0,20],zoom:1.35,bearing:0,pitch:0,duration:1000});clearLayer('selected-orbit');state.selected=null;toast('Global view restored')}
document.querySelectorAll('.layer').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('active');updateVisibility()}));$('refreshBtn').onclick=load;$('resetBtn').onclick=resetView;$('issBtn').onclick=()=>{const s=state.satellites.find(x=>/\bISS\b|ZARYA|25544/i.test(satelliteName(x)+' '+satelliteId(x)));s?focusSatellite(s):toast('ISS is not in the current feed')};$('orbitMode').onchange=async()=>{if(state.selected&&$('orbitMode').checked)await drawOrbit(state.selected);updateVisibility()};$('autoRefresh').onchange=()=>toast($('autoRefresh').checked?'Auto refresh enabled':'Auto refresh paused');$('nightMode').onchange=()=>{$('nightMode').checked=true;toast('Globe projection is always enabled')};$('search').addEventListener('input',e=>searchSatellites(e.target.value));document.addEventListener('click',e=>{if(!e.target.closest('.searchbox'))$('searchResults').classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('search').focus()}if(e.key.toLowerCase()==='f'){if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()}if(e.key.toLowerCase()==='r'&&document.activeElement.tagName!=='INPUT')resetView()});setInterval(()=>{$('clock').textContent=new Date().toISOString().slice(11,19)+' UTC'},1000);setInterval(()=>{if($('autoRefresh').checked)load()},60000);map.on('load',load);
